### ISSUE TITLE
Manta E3EZ Step and PDF files in 3D directory in this repository appear to be corrupt.

### ISSUE THREAD

**Issue by Cruzg74** [bigtreetech/Manta-E3EZ#23]
I tried downloading the .step file but it will not open in in Solidworks,Fusion 360, or FreeCAD. All three report that it is an invalid file. I also tried opening the PDF version and just get a blank page. Please re-upload known working files.

**Comment by Cruzg74** [comment]
So it appears that the file work fine when you download the entire repository as opposed to individual files. Strange, but it's working.

**Comment by Dids** [comment]
This is due to Git LFS.
