### ISSUE TITLE
Manta E3EZ+CB1+EBB36 v1.2 

### ISSUE THREAD

**Issue by alexandrugai** [bigtreetech/Manta-E3EZ#9]
hi there...i need some help. yesterday arrived the ebb36 v1.2 and i'm trying to connect it to manta e3ez over can. manta flashed with klipper and selected "usb to can bus bridge (usb on PA11/PA12 and canbus on PB8/PB9)" and here begins the problem... when flashed this way, CB1 doesn't recognize manta anymore over "usb serial" connection. can0 network appears, but just the manta, not the ebb36. to mention that when i try to flash the ebb36 with stmcube i get an error "download failed" or something like this but when i flash it with canboot, flashes ok. in the manta manual i didn't found nothing about can bus. after first attempt to flash the ebb, it remains with one led full lit and the other one barely visible.

**Comment by hauserkristof** [comment]
Hi @alexandrugai !

Did you manage to set up the EBB36 with the E3EZ?

If yes, than how? Can you help me with it please?

Thanks
